### PR TITLE
add STRUMPACK test

### PR DESCRIPTION
**Pull request by pghysels**

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
@pghysels thanks for the contribution. I will wait for @wspear to merge https://github.com/E4S-Project/testsuite/pull/14 and then we can test this out. 

It's not exactly the type of test I was looking since it depends on E4S Testsuite, it would be good to know if this test will run to competition. 

Could you add yourself as maintainers to the test.

https://github.com/buildtesters/buildtest-cori/blob/2a5da08b7bac6314a4594a0af92d23a9c55065f9/buildspecs/e4s/e4s_21.05.yml#L75-L77

**Comment by pghysels** [comment]
This should still work without the changes from https://github.com/E4S-Project/testsuite/pull/14

If you don't want it to depend on E4S Testsuite, you can just copy the test, but then we are duplicating it.

I tried to check the output for "Success" with a regex, but I could not get that to work.

**Review by shahzebsiddiqui — APPROVED** [review]

**Comment by shahzebsiddiqui** [comment]
Oh yes i see what you mean. I just realized this test already exist and your PR was just changing the existing test in E4S Testsuite.

**Comment by shahzebsiddiqui** [comment]
@pghysels i granted you access to https://software.nersc.gov/NERSC/buildtest-cori which is the source repo and this repo is the mirror. This was recently changed so if you would contribute back in future please send MR in the gitlab repo.

**Pull request merged**
