### PR TITLE
OESS-167:add hdf5 develop-1.10 tests.

### PR DESCRIPTION
**Pull request by hyoklee**

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
@hyoklee thank you for your contribution. I don't think we have `hdf5@develop-1.10%gcc` and `hdf5@develop-1.10%intel` spec in our `e4s/21.02` and `e4s/21.05` module.

These are the versions we have for `e4s/21.05`

```
(buildtest) siddiq90@cori12> module load e4s/21.05
(buildtest) siddiq90@cori12> spack find --format "{name}@{version}%{compiler} {variants}" hdf5
hdf5@1.8.22%intel@19.1.3.304 ~cxx~debug+fortran+hl~java+mpi+pic+shared~szip~threadsafe api=none
hdf5@1.10.7%intel@19.1.3.304 ~cxx~debug+fortran+hl~java+mpi+pic+shared~szip~threadsafe api=none
```

I know we have a pipeline by @lrknox https://software.nersc.gov/ecp/e4s-ci-pipelines/hdf5 which has some `hdf5@develop` specs. If these specs can be installed from buildcache then we can certainly have a test that will take a predefined `spack.yaml` and just install and test the package.

I think this PR will need to be refactored.

**Comment by hyoklee** [comment]
@shahzebsiddiqui, thanks for the detailed comment. I'm new to buildtest-cori and I thought that it directly tests HDF5 package available in https://github.com/spack/spack repo that defines develop-1.10 branch. I wish you can clarify the relationship among these repos:

1. https://github.com/spack/spack
2. https://software.nersc.gov/ecp/e4s-ci-pipelines/hdf5 
3. https://github.com/buildtesters/buildtest-cori

Everything is obscure in documentation. builtest-cori needs a simple tutorial / FAQ for contributors.

**Comment by shahzebsiddiqui** [comment]
Yes let me clarify the relationship.

https://github.com/spack/spack: I am sure you are familiar with spack. 

https://software.nersc.gov/ecp/e4s-ci-pipelines/hdf5 : this is nightly builds of HDF5 which is meant to build HDF5 via spack on a regular basis. I am part of the Software Integration team in ECP and we are responsible for building e4s on quarterly release. Currently we have three release `e4s/[20.10|21.02|21.05]` for more details see https://docs.nersc.gov/applications/e4s/. We have a page for [Spack Gitlab Pipeline](https://docs.nersc.gov/applications/e4s/spack_gitlab_pipeline/) in our NERSC docs that can help ECP teams get started. We have a few other pipelines for nightly builds of E4S products.

https://github.com/buildtesters/buildtest-cori: This is the test repository for Cori/Perlmutter using [buildtest](https://buildtest.readthedocs.io/en/devel/index.html). This repo contains facility test examples that is only applicable for Cori and Perlmutter system. Most of the tests are for Cori but soon we will have more tests for Perlmutter.

There is a [contributing guide](https://github.com/buildtesters/buildtest-cori/blob/devel/CONTRIBUTING.md) for this repo and I think you did the thing by issuing PR to `devel` branch.

If you are new to buildtest please see the [docs](https://buildtest.readthedocs.io/) and join the [slack channel](https://hpcbuildtest.herokuapp.com/) if you need help. buildtest has [spack integration](https://buildtest.readthedocs.io/en/devel/buildspecs/spack.html) to help write tests which is one of the way we are testing e4s stack by leveraging **spack test**. Note that we are using `spack test` on facility deployment of e4s which is a **fixed** version of spack hence we may not have all the tests available via `spack test` depending on the spack commit. We use the e4s release provided in this project [E4S-Project/e4s](https://github.com/E4S-Project/e4s) and they provide release in form of `spack.yaml` see [environments](https://github.com/E4S-Project/e4s/tree/master/environments) directory for e4s releases.

**Comment by hyoklee** [comment]
Pointing me a bunch of URLs doesn't help me much.

So, which file should I modify to add develop-1.10 test?

1. https://software.nersc.gov/ecp/e4s-ci-pipelines/hdf5/-/blob/main/.gitlab-ci.yml
2. https://software.nersc.gov/ecp/e4s-ci-pipelines/hdf5/-/blob/main/spack.yaml
3. Both 1. and 2.

If 1, where should I modify? Should I add 

```
- spack install --no-checksum hdf5@develop-1.10+fortran+cxx+hl
```
under script: section?

If 2, where should I modify? Should I add ```- hdf5@devel-1.10``` here?
```
 specs:     
    - hdf5@1.12.1
    - hdf5
```
If 3, will the above change be sufficient?
Thanks in advance!

**Comment by shahzebsiddiqui** [comment]
Hi @hyoklee,

So if you want to run test for `hdf5@develop-1.10` then it should be in this repo we just need to write a test that will install the spec from buildcache assuming it is already built and can be installed via spack. The way your proposed test is written will not work because there won't be such spec to test and spack will just ignore it.

It will look something like this

```
spack test run hdf5@develop-1.10
==> Warning: No installed packages match spec hdf5@develop-1.10
==> Spack test 6fguo6pujncfzxtjiwne2d77zwlxt3pw
```

 If you take a look at the latest run of hdf5 https://my.cdash.org/test/40209168 you will see an example content of generated test. Our `module load e4s/21.05` will provide a spack instance with pre-installed specs. For `hdf5` you will need to write a test such that it does a `spack install` followed by `spack test`.


Screen Shot 2021-08-31 at 12 20 57 PM

**Comment by hyoklee** [comment]
> What i am proposing is you provide a `spack.yaml` so that it can provide all the spack configuration and just install the spec.

Where should I provide spack.yaml?
Are you talking about https://software.nersc.gov/ecp/e4s-ci-pipelines/hdf5/-/blob/main/spack.yaml ?

**Comment by shahzebsiddiqui** [comment]
no not that this spack.yaml (https://software.nersc.gov/ecp/e4s-ci-pipelines/hdf5/-/blob/main/spack.yaml ) but what you want is a `spack.yaml` that can install hdf5 as any user. Take a look at https://docs.nersc.gov/applications/e4s/cori/21.05/#spack-workflow on how one can just specify a `spack.yaml` and install a spec from buildcache. This assumes one has path to mirror and spack concretizes the spec to same hash. The content would look very similar to one in https://software.nersc.gov/ecp/e4s-ci-pipelines/hdf5/-/blob/main/spack.yaml but it would be different.

I think your first step is as a user login to Cori and install the spec from buildcache that will help you test the package in user space and then write a buildspec that can test the package via buildtest.

When installing from buildcache one needs to install the GPG key this can be `spack buildcache keys -it` if GPG key is part of the mirror. If its on the filesystem one needs access to gpg key atleast read access so one can do `spack gpg trust /path/to/gpg`. The [e4s/21.02 docs](https://docs.nersc.gov/applications/e4s/cori/21.02/#installing-software-via-spack) has a good workflow on installing specs from buildcache and module generation.

**Comment by shahzebsiddiqui** [comment]
@hyoklee i am going to close this PR since this test is not applicable.

**Pull request closed without merging**
